modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="chained"
version="${file.jarVersion}"
displayName="Chained"
#displayURL="http://example.com/"
authors="IchHabeHunger54"
description='''
Adds chains and chain horse armor, as well as recipes for chain armor and the various vanilla horse armors.
'''
#[[dependencies.chained]]
#    modId="forge" #mandatory
#    mandatory=true #mandatory
#    versionRange="[28,)" #mandatory
#    ordering="NONE"
#    side="BOTH"
#[[dependencies.chained]]
#    modId="minecraft"
#    mandatory=true
#    versionRange="[1.14.4]"
#    ordering="NONE"
#    side="BOTH"
