modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="chained"
version="${file.jarVersion}"
displayName="Chained"
displayURL="http://www.curseforge.com/minecraft/mc-mods/chained"
authors="IchHabeHunger54"
description='''
Adds chains and chain horse armor, as well as recipes for chain armor and the various vanilla horse armors.
'''
[[dependencies.chained]]
modId="forge"
versionRange="[36,)"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.chained]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
